services:
  db:
    container_name: mysql
    image: mysql
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=khaddemapp
    ports:
      - '3306:3306'
    volumes:
      - mysql:/var/lib/mysql
      - $PWD/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
  spring_app:
    container_name: kaddem
    image: chawkimersani-5sae2-g2
    restart: on-failure
    build: .
    ports:
      - 8089:8089
    depends_on:
      - db

